# Generated by Django 5.2.5 on 2025-09-28 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addressmodel',
            name='address_line',
        ),
        migrations.RemoveField(
            model_name='addressmodel',
            name='country',
        ),
        migrations.RemoveField(
            model_name='addressmodel',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='addressmodel',
            name='state',
        ),
    ]
