# Generated by Django 5.2.5 on 2025-08-13 10:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_user_options_alter_user_managers_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                default="user@mail.com", max_length=254, unique=True
            ),
            preserve_default=False,
        ),
    ]
