# Generated by Django 5.2.5 on 2025-10-03 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('categoryId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('icon', models.CharField(blank=True, help_text='Lucide icon name for this category. You can obtain a name from https://lucide.dev/icons/', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('productId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='catalog.category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('variantId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tradeInPrice', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stockQuantity', models.PositiveIntegerField(default=0)),
                ('isInStock', models.BooleanField(default=True)),
                ('images', models.JSONField(blank=True, default=list)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.product')),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('offerId', models.AutoField(primary_key=True, serialize=False)),
                ('isActive', models.BooleanField(default=True)),
                ('offerPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('startDate', models.DateTimeField()),
                ('endDate', models.DateTimeField()),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='catalog.productvariant')),
            ],
        ),
    ]
