# Generated by Django 5.0.6 on 2025-10-03 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_remove_category_categoryid_remove_offer_offerid_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='CategoryModel',
        ),
        migrations.RenameModel(
            old_name='Offer',
            new_name='OfferModel',
        ),
        migrations.RenameModel(
            old_name='Product',
            new_name='ProductModel',
        ),
        migrations.RenameModel(
            old_name='ProductVariant',
            new_name='ProductVariantModel',
        ),
    ]
