# Generated by Django 5.2.5 on 2025-10-14 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_rename_category_categorymodel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariantmodel',
            name='images',
        ),
        migrations.CreateModel(
            name='ProductVariantImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product-variant-images/')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.productvariantmodel')),
            ],
        ),
    ]
