# Generated by Django 5.2.5 on 2025-10-31 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_remove_productvariantmodel_images_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="categorymodel",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Category image",
                null=True,
                upload_to="category-images/",
            ),
        ),
    ]
